### ISSUE TITLE
pi zero 2 wch can't recognizer by pinout cli

### ISSUE THREAD

**Issue by hotrungnhan** [gpiozero/gpiozero#1031]
Hello guy , i found some issue with the new pi zero 2 wch (has gpio pin soldererd)
Pinout CLI didn't recognizer my pi zero 2 wch by from cytron. 
It have revision code is 902120
![image](https://user-images.githubusercontent.com/40029631/157488278-c8c16085-b351-47fc-823c-c6c54c7c347c.png)
This line below will be equal to 8 which stands for pi 3. 
https://github.com/gpiozero/gpiozero/blob/2b6aa5314830fedf3701113b6713161086defa38/gpiozero/pins/data.py#L1011

**Comment by lurch** [comment]
Already fixed by #1004 , but there's not been a stable [release](https://github.com/gpiozero/gpiozero/tags) of GPIO Zero since March 2021. ping @bennuttall

**Comment by hotrungnhan** [comment]
tks you for help, i'm willing to waiting for the new stable release
