### ISSUE TITLE
Motor class remote

### ISSUE THREAD

**Issue by gnicki2000** [gpiozero/gpiozero#1042]
I´m using Raspi zero 2 w. The Motor class doesen´t work via remote factory. LED and Servo work fine so it can´t be hardware or connection. But still Motor says it can´t connect. See: https://stackoverflow.com/questions/72163157/raspi-remote-gpio-pizero-problems

**Comment by lurch** [comment]
Fixed by #792 ?

**Comment by gnicki2000** [comment]
Thank you verry much. The 
super(Motor, self).__init__(_order=devices.keys(), **pin_factory=pin_factory,** **devices)
in line 1223 ist sill missing when installing gpiozero via pip install.
