### ISSUE TITLE
No module named 'lgpio'

### ISSUE THREAD

**Issue by EDIflyer** [gpiozero/gpiozero#1120]
Operating system: Raspberry Pi OS (Legacy) Lite (Bullseye, Kernel 6.1, 5/12/23)
Python version: 3.9.2
Pi model: Pi Zero W
GPIO Zero version: gpiozero-2.0.1-py3-none-any.whl
Pin factory used: RPi.GPIO-0.7.1-cp39-cp39-linux_armv6l.whl

I have code that utilises Luma OLED and a touch controller and was working well on a previous installation, doing a new install of Bullseye and getting this error when trying to initialise the display:
```
/usr/local/lib/python3.9/dist-packages/gpiozero/devices.py:300: PinFactoryFallback: Falling back from lgpio: No module named 'lgpio'
  warnings.warn(
Traceback (most recent call last):
  File "/home/pi/./display_menu.py", line 1707, in <module>
    observer.start()
  File "/usr/local/lib/python3.9/dist-packages/watchdog/observers/api.py", line 280, in start
    emitter.start()
  File "/usr/local/lib/python3.9/dist-packages/watchdog/utils/__init__.py", line 92, in start
    self.on_thread_start()
  File "/usr/local/lib/python3.9/dist-packages/watchdog/observers/inotify.py", line 125, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive, event_mask)
  File "/usr/local/lib/python3.9/dist-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
    self._inotify = Inotify(path, recursive, event_mask)
  File "/usr/local/lib/python3.9/dist-packages/watchdog/observers/inotify_c.py", line 176, in __init__
    self._add_watch(path, event_mask)
  File "/usr/local/lib/python3.9/dist-packages/watchdog/observers/inotify_c.py", line 401, in _add_watch
    Inotify._raise_error()
  File "/usr/local/lib/python3.9/dist-packages/watchdog/observers/inotify_c.py", line 417, in _raise_error
    raise OSError(err, os.strerror(err))
FileNotFoundError: [Errno 2] No such file or directory
```
Running the Python file with sudo too so no write access permission issues as noted in #1106

**Comment by lurch** [comment]
It looks like perhaps the nested-exception-handling in GpioZero is producing slightly misleading output, ad obscuring the real error.
When you do ` observer.start()` in your code, what `path` ultimately filters through to `self._add_watch(path, event_mask)` ? Perhaps that's the path causing the `FileNotFoundError` ?

**Comment by EDIflyer** [comment]
Thanks for the reply @lurch.

It appears the watchdog error was unrelated and just due to a directory I hadn't created on a new installation!

Everything is now working however in my logs I still get that initial `lgpio` error:
``` bash
/usr/local/lib/python3.9/dist-packages/gpiozero/devices.py:300: PinFactoryFallback: Falling back from lgpio: No module named 'lgpio'
  warnings.warn(
```

The code is:
``` python
from gpiozero import Button
try:
    buttonpress = Button(4, pull_up=True)
except:
    logger.exception(" Unable to set GPIO pin")
```
I added some extra statements to check and it is definitely just after trying to create `buttonpress` that the warning pops up, albeit it's not enough to trigger an exception.

**Comment by lurch** [comment]
That's just a warning, not an error. Nothing to worry about.

> Everything is now working...

Hurrah! :tada:

**Comment by EDIflyer** [comment]
Ah OK that's good to hear - I was updating from an older version of Raspberry Pi OS so thought I'd broken something at first! Presumably this is just a newer version of gpiozero that supports multiple methods and lgpio is some new one that's not supported on the Pi Zero W?

**Comment by lurch** [comment]
RPi.GPIO _used_ to be the default pin-library in GpioZero, but RPi.GPIO doesn't work on the Pi 5; so in the latest version of GpioZero the ordering of the pin-libraries were changed so that it looks for lgpio first, and if it doesn't find that it uses RPi.GPIO instead. More docs at https://gpiozero.readthedocs.io/en/latest/api_pins.html#changing-the-pin-factory

And the reason that you don't have lgpio installed is because you're still using Raspberry Pi OS Bullseye rather than RPi OS Bookworm (on Bookworm, which is the first OS to support the Pi5, lgpio is installed by default).

**Comment by EDIflyer** [comment]
Really interesting explanation, thanks @lurch.

Yes, downloaded Bookworm initially when upgrading, however although it says all models supported the RPi imager doesn't seem to recommend it so stuck with Bullseye for now as it's a bit of a pain to do the headless setup compared to previously!

**Comment by lurch** [comment]
Just as a followup: the docs already explain how to suppress that warning message: https://gpiozero.readthedocs.io/en/stable/faq.html#why-do-i-get-pinfactoryfallback-warnings-when-i-import-gpiozero
