### ISSUE TITLE
Support for: Raspberry Pi Pico (+Pico W) Remote GPIO?

### ISSUE THREAD

**Issue by PizzaProgram** [gpiozero/gpiozero#1127]
Device name: **Raspberry Pi Pico**
Protocol: **GPIO** + SPI + I2C + built-in TEMP + PWM + AVC
URL: https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html

The RPi Pico board family is a cheap (~ $4) and great product, available since ca. 2022 with many GPIOs and features.
Both Pico + PicoW can be attached by an USB port. (The W = Wifi.)

There are many code examples out there, like:
- [Firmata-Pico](https://github.com/firmata/ConfigurableFirmata/issues/115) _lang:_ C, C++
- [Arduino-Pic](https://arduino-pico.readthedocs.io/en/latest/index.html) _lang:_ C , C++
- [u2if](https://github.com/execuc/u2if) _lang:_ **MicroPython**  ... can not support multiple boards attached!

But none of them support:
- industrial CRC during _(USB = serial)_ communication
- proper error handling _(disconnect / reconnect)_
- ping / keepalive checks
- plug & play 
- easy naming of the board ( robot2, roller-shutter11, basementLight23, temp47, ...)

# The Taks:
... would be to use this great codebase and create a universal firmware for Pico boards to be able to communicate with them.

```python
from gpiozero import Pico, PicoW 
pUsb1 = Pico.searchByName('ceilingLight')
pW2 = PicoW.connectByIP('192.168.42.42')

garden = pW2.OutputDevice(17)
```

**Comment by lurch** [comment]
I guess this is a similar idea to https://gpiozero.readthedocs.io/en/latest/pi_zero_otg.html but "creating universal firmware for Pico boards" is definitely outside of the remit of this particular repo!
