### ISSUE TITLE
TimeOfDay questions

### ISSUE THREAD

**Issue by lurch** [gpiozero/gpiozero#263]
1) Why does the `utc` parameter default to True? I'd expect most users to want to schedule things using their local time rather than UTC time?

2) Perhaps the example would benefit from at least one of the example times having a minutes component to it.

3) More of a longer-term question... (no pun intended!)
I guess _effectively_ TimeOfDay is acting as a start_time in combination with a timedelta. Perhaps we should allow more flexibility with the start_time value, e.g. using your example, maybe the user only wants to turn on their lamp on Wednesday mornings? (or at a different time on weekends compared to weekdays?)
I've got a gut-feeling that this is kind of like an overlap with cron-based functionality, so did a quick search and found http://stackoverflow.com/questions/373335/how-do-i-get-a-cron-like-scheduler-in-python which has a number of suggestions for starting-points that we could use if we decided to expand on this.

**Comment by waveform80** [comment]
1. Couple of reasons - firstly that Raspbian defaults to UTC so (by default) the timezone on a Pi is UTC anyway and secondly I'm always extremely wary of timezone usage (having experienced the hell of Windows servers in data-centers throwing wobblies over daylight savings times). If Raspbian defaulted to something other than UTC, I'd consider making the default non-UTC but as it is this seems the most reasonable default.

2. Very likely - these were very quickly thrown together - more examples welcome!

3. Yup - I started hacking together a date one and then immediately thought "hang on, what if I want to execute on the second to last Thursday in a month" and decided to stop until I had some time to seriously address how to do that. As it stands, `other_devices` is very much a rough sketch - I wouldn't even consider its API locked down yet (it's also largely untested). Suggestions / PRs most welcome!
