### ISSUE TITLE
Privacy breach: local documentation shouldn't include Travis build status

### ISSUE THREAD

**Issue by EdwardBetts** [gpiozero/gpiozero#295]
As discussed in #284.

The documentation available at http://gpiozero.readthedocs.org/en/latest/ includes the Travis build status. This is useful.

The build status shouldn't be included in the documentation intended to be read offline, specifically in the Debian package of documentation.

**Comment by waveform80** [comment]
Thanks for the reminder ticket - I'll see what I can do about this for the next release

**Comment by waveform80** [comment]
ARGH! Bloody PyPI doesn't work with the damned thing either. Right, sorry about this but I'm going to have to revert the change - it just breaks too many things and I've got no time to fix it now. If someone wants to do a proper fix later (whatever that may entail), be my guest.

**Comment by lurch** [comment]
Was this closed again accidentally? Should it be re-opened?

**Comment by waveform80** [comment]
Bah, yeah that's GitHub reacting to the "Fix" in the title without seeing the "Revert" which git bunged before it.

**Comment by waveform80** [comment]
Fixed in a2b2b816510cebdbd2e4cb56906b2fe27e8bbf7e
