### ISSUE TITLE
pigpio pwm does not support float frequencies

### ISSUE THREAD

**Issue by bennuttall** [gpiozero/gpiozero#712]
Operating system: Raspbian Stretch
Pi model: e.g. Pi 3 Model B+
GPIO Zero version: e.g. 1.4.1
Pin factory used: e.g. pigpio

RPiGPIOPin will happily take float values as its PWM device frequency, but pigpio falls over if you try to send a float. The following code will work for RPiGPIOPin but not for PiGPIOPin:

```python
>>> pwm = PWMOutputDevice(20)
>>> pwm.frequency = 500.0
```

The following error occurs (truncated stack trace):

```python
/usr/lib/python3/dist-packages/pigpio.py in _pigpio_command(sl, cmd, p1, p2, rl)
    981    """
    982    sl.l.acquire()
--> 983    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
    984    dummy, res = struct.unpack('12sI', sl.s.recv(_SOCK_CMD_LEN))
    985    if rl: sl.l.release()

error: required argument is not an integer
```

Also the pigpio connection seems to hang after this, so you can't carry in after an error like this in the shell. You can't even exit the shell without forcing it.

As discussed with @waveform80 we need to address this in pins API in v1.6.

**Comment by ForToffee** [comment]
Just tripped over this using gpiozero on x86 raspbian to a pizero as gpio extender.

I've put in a work around to int() the value before it is passed to the factory in _set_frequency in pigpio.py.

Any idea when this will be fixed?

**Comment by bennuttall** [comment]
> I've put in a work around to int() the value before it is passed to the factory in _set_frequency in pigpio.py.

Yeah I tried that but it's more complicated. I'll take a look when I get chance but I think it's probably one for @waveform80.

**Comment by ForToffee** [comment]
From what I experienced last night the issue appears to be self.factory.connection.set_PWM_frequency() on lines 300 and 306.  Wrapping value on these two lines in int() fixed it.  What's the bit I'm missing if this isn't the correct way of resolving this?

It's a pain as I'm setting up a session using laptops and PiZeros in extender mode which relies on pigpio

**Comment by bennuttall** [comment]
Did it fix it in a way that made TonalBuzzer work properly, or just make the error go away? I seem to recall only managing the latter

**Comment by ForToffee** [comment]
Yes, TonalBuzzer does work (i.e. it plays a tone, rather than error out).  I've (hopefully) created a PR for you.
