### ISSUE TITLE
Are there plans to support I2C?

### ISSUE THREAD

**Issue by jikoy** [gpiozero/gpiozero#778]
Are there plans to support I2C?

**Comment by bennuttall** [comment]
Eventually, yes.

**Comment by jikoy** [comment]
Oh yeah. Great!发自我的华为手机-------- 原始邮件 --------主题：Re: [gpiozero/gpiozero] Are there plans to support I2C? (#778)发件人：Ben Nuttall 收件人：gpiozero/gpiozero 抄送：jikoy ,Author Eventually, yes.

**Comment by hyansuper** [comment]
Great ！I've been waiting for remote gpio through i2c to control a ssh1106 LED display
