### ISSUE TITLE
Simple button

### ISSUE THREAD

**Issue by TGWC** [gpiozero/gpiozero#784]
I want to use 3 simple buttons. Can I just plig them in? Or do I have to add resistors? Can put only 10k in the ground part of each button? or should I made the ull up/down with resistors? What are the real issues without making external pull up/down ?

**Comment by bennuttall** [comment]
You can use buttons without resistors, and use the software-controlled pull-ups.

Any further questions, or for more detail, I'd suggest you ask in the [forums](https://www.raspberrypi.org/forums).
