### ISSUE TITLE
Cannot make it work with FLASK GEVENT

### ISSUE THREAD

**Issue by TGWC** [gpiozero/gpiozero#788]
When using with Flask and Gevent all background threads do not work, how to solve it?

**Comment by bennuttall** [comment]
I can't imagine that threads will work nicely with web frameworks. You'll need to bridge the gap with some code running aside from the web app. Not an easy one to answer. I'd suggest you try the [forums](https://www.raspberrypi.org/forums/viewforum.php?f=32) for advice.

Note issues here are not intended for troubleshooting, rather reporting bugs or suggesting features.
