### ISSUE TITLE
Set pulse_width on Servo / PWMOutputDevice

### ISSUE THREAD

**Issue by bennuttall** [gpiozero/gpiozero#795]
It's currently not possible to set the pulse width of a servo or PWM device. There's a `pulse_width` property in `Servo`, but only a getter, not a setter. I added one and tested it with @evildmp and it seemed to work:

```python
@property
def pulse_width(self):
    if self.pwm_device.pin.frequency is None:
        return None
    else:
        return self.pwm_device.pin.state * self.frame_width

@pulse_width.setter
def pulse_width(self, value):
    self.pwm_device.pin.state = value / self.frame_width
```

I think this could be added lower down, in `PWMOutputDevice`.

**Comment by joan2937** [comment]
Setting the pulse width is the only correct way of controlling a servo.

A servo moves to a central position if given a 1500µs pulse.  A duty cycle of 7.5% happens to give a 1500µs pulse if PWM is 50Hz.  Change the duty cycle (many servos can cope with lower or higher update rates) and the pulse width also changes which drives the servo to the wrong position,

**Comment by bennuttall** [comment]
@joan2937 currently the user can set a "value" between -1 (min pulse width) and 1 (max pulse width). We are calculating the appropriate pulse width and setting it directly, but the user can't set it themselves.

**Comment by lurch** [comment]
Given the "abstraction layer" that GpioZero places over servos, what benefit does setting the pulse width directly (instead of just setting its "value") have?

**Comment by bennuttall** [comment]
@evildmp has a project where he's calculating the required pulse width and setting directly. He's not even using a linear angle -> pulse width calculation, because he's found it to be inaccurate. He's not currently able to use gpiozero, but is having great success with pigpio.

**Comment by lurch** [comment]
Ahhh, yeah I guess non-linear servos is a good use-case :slightly_smiling_face:

**Comment by joan2937** [comment]
@bennuttall  Is that https://github.com/evildmp/BrachioGraph ?

I like the drawings.  I don't see why it can't be done with gpiozero though.  I assume that there is a mapping from 0..1 to a pulse width and vice versa.
