### ISSUE TITLE
API for addressable LED strip WS2812 

### ISSUE THREAD

**Issue by maharshi114** [gpiozero/gpiozero#807]
WS2812 is an addressable LED strip with a 30/60/144 LEDs option. 
I am searching for all other ways but I couldn't find it in GPIOzero. 

Product Link: https://robu.in/product/1m-ws2812b-5v-addressable-rgb-non-waterproof-led-strip-light-60leds-m/?gclid=EAIaIQobChMI4LHHndD85AIVFouPCh3HMQLvEAQYASABEgLVtvD_BwE

**Comment by lurch** [comment]
See also #551 and #583

**Comment by bennuttall** [comment]
We have an existing issue for this #583 but no movement so far. Neopixels are a complex device which require precise timing. For now you probably want to use https://pypi.org/project/rpi-ws281x/ or maybe pigpio?
