### ISSUE TITLE
Possible to group pins together for state change?  (re: waiting for one of many pins to change)

### ISSUE THREAD

**Issue by sofakng** [gpiozero/gpiozero#839]
I'm trying to interface with a device that requires 3 GPIO pins:

Pin 1: IN_BIT0
Pin 2: IN_BIT1
Pin 3: IN_BIT2

Together, these represent an integer from 0 to 7.

When ANY of the bits change, I need to read the state of all 3 to determine the current value.

Does gpiozero provide any methods for doing this or can anybody provide me guidance?

**Comment by bennuttall** [comment]
Ooh that's nice.

Yes - I'd use `ButtonBoard`, a class which wraps around any number of buttons.

ButtonBoard example:

```python
>>> from gpiozero import ButtonBoard
>>> bb = ButtonBoard(2, 3, 4)
>>> tuple(bb.value)
(0, 0, 0)
# check it again while a button is pressed
>>> tuple(bb.value)
(0, 1, 0)
# check it again while a button is pressed
>>> tuple(bb.value)
(1, 1, 0)
```

Essentially ButtonBoard provides the binary number in `.value` in the form of a tuple, so you're half way there.

`Number` implementation:

```python
from gpiozero import ButtonBoard

class Number(ButtonBoard):
    def __init__(self, bit_0_pin, bit_1_pin, bit_2_pin, **kwargs):
        self.super().__init__(bit_0_pin, bit_1_pin, bit_2_pin, **kwargs)

    @property
    def number(self):
        # convert .value tuple (bit0, bit1, bit2) into a binary string and return the int value
        return int(''.join(str(bit) for bit in self.value), 2)
```

Then you would read it like so:

```python
>>> n = Number(2, 3, 4)
>>> n.number
0
# check it again while a button is pressed
>>> n.number
2
# check it again while another button is pressed
>>> n.number
6
```

If you want something to happen when it changes, and not have to poll it, you should be able to set `when_changed` on your ButtonBoard/Number object:

```python
>>> n.when_changed = lambda bb: print(bb.number)
```

or without a lambda:

```python
>>> def foo(bb):
...     print(bb.number)
>>> n.when_changed = foo
```

I'm assuming you're using buttons as inputs. If not, this will still work but you'll probably need to switch the pull-up flag (buttons assume pull-up by default):

```python
>>> ButtonBoard(2, 3, 4, pull_up=False)
# or
>>> Number(2, 3, 4, pull_up=False)
```

Hope that helps!
