### ISSUE TITLE
PingServer - name 'devnull' is not defined

### ISSUE THREAD

**Issue by SteveAmor** [gpiozero/gpiozero#844]
Operating system: Raspbian Buster (clean install)
Python version: 2.7.16 & 3.7.3
Pi model: Pi 3
GPIO Zero version: 1.5.1
Pin factory used: RPiGPIO
See http://rpf.io/gpzissue for information on how to find out these details

Should this return a boolean?

```python
>>> from gpiozero import PingServer
>>> PingServer("google.com")
<gpiozero.PingServer object host="google.com">
```

**Comment by bennuttall** [comment]
No - use `PingServer` the same way you'd use `Button`. Create an instance, and ask for its value:

```python
>>> from gpiozero import PingServer
>>> google = PingServer("google.com")
>>> google.value
1
```

See the docs: https://gpiozero.readthedocs.io/en/stable/api_internal.html#pingserver

**Comment by SteveAmor** [comment]
Thanks Ben
