### ISSUE TITLE
Distance Sensor Documentation states incorrect default value for queue_len

### ISSUE THREAD

**Issue by linucks** [gpiozero/gpiozero#858]
GPIO Zero version: dda329b51c7226fd71cf7ff03a27422549121242

The Pydoc for [DistanceSensor](https://github.com/gpiozero/gpiozero/blob/dda329b51c7226fd71cf7ff03a27422549121242/gpiozero/input_devices.py#L753) states the default queue_len is 30, but in the constructor it's 9.

**Comment by bennuttall** [comment]
Thanks! Fixed
