### ISSUE TITLE
Help with BMP180 sensor and gpiozero

### ISSUE THREAD

**Issue by natalia-fernandes** [gpiozero/gpiozero#878]
Hi folks.

I'm a newbie in Raspberry, and I'm trying to fetch data from a [BMP180](https://thepihut.com/blogs/raspberry-pi-tutorials/18025084-sensors-pressure-temperature-and-altitude-with-the-bmp180) using gpiozero (I connected the BMP180 using the layout on this link).

In the documentation I cannot find a way to do that. In the [device class](https://gpiozero.readthedocs.io/en/stable/api_generic.html#device) I can see that gpiozero supports i2c devices, but it is not clear how I can instantiate this device in the application.

Could someone please give me a hint about this?

I'm using a Respberry 4.

Best regards

**Comment by bennuttall** [comment]
Sorry, gpiozero doesn't currently support I2C.
