### ISSUE TITLE
PIGPIO_ADDR=192.168.1.3 python3

### ISSUE THREAD

**Issue by CTECH9** [gpiozero/gpiozero#885]
Short description of change: Make Windows-specific environment variables for remote GPIO
Where would this change be made: e.g. Chapter 4.3

Purpose of change:

The environment variables provided do not work with the Windows 10 version of python, they are for Unix-based operating systems.

**Comment by waveform80** [comment]
PRs welcome?

**Comment by CTECH9** [comment]
I am dumb. I didn't know what I was doing and I didn't read the entire documentation. You may ridicule me as much as you like. I'm going to close the issue.

**Comment by waveform80** [comment]
Heh, no problem :) I did wonder if I was missing something as I *thought* it should "just work" under Windows, but unfortunately I haven't got any Windows machines around here at the moment to test on. Anyway, glad to hear it's sorted!
