### ISSUE TITLE
TonalBuzzer error when using remote factory started from Windows10

### ISSUE THREAD

**Issue by ITSM-79** [gpiozero/gpiozero#917]
I ran the following code on a Windows10 PC to test the TonalBuzzer, which resulted in the traceback messages shown below. I then transferred the same code to the RPi and removed the pin_factory information. This resulted in no errors.

PC and RPi are running gpiozero 1.5.1. I have experience no issues when using the pin_factory in other programs (i.e. just blinking LEDs or collecting button presses)

The instance of 'Tone' appears to be created correctly as the output for "type(tone)" and "tone.frequency()" and "tone.note()" are all OK. I also tried using "buzzer.play(Tone(220.0))" and other variations but received the same result no matter how I pass the argument for tone into the 'play' method.

All errors come back with the same "required argument is not an integer" error from pigpio. pigpio is latest version (1.78)

#### CODE for WINDOWS 10 ####

from gpiozero import TonalBuzzer
from gpiozero.pins.pigpio import PiGPIOFactory
from gpiozero.tones import Tone

RPi = '192.168.0.81'
factory = PiGPIOFactory(host=RPi)
buzzer = TonalBuzzer(26, pin_factory=factory)

tone = Tone(220.0)
print(type(tone))
print(tone.frequency)
print(tone.note)

buzzer.play(tone)
sleep(2)
buzzer.stop()

### TRACEBACK on WINDOWS 10 ####

<class 'gpiozero.tones.Tone'>
220.0
A3   
Traceback (most recent call last):
  File "[...]\TonalBuzzer_test.py", line 14, in <module>
    buzzer.play(tone)
  File "C:\Program Files\Python\lib\site-packages\gpiozero\output_devices.py", line 694, in play
    self.pwm_device.pin.frequency = freq
  File "C:\Program Files\Python\lib\site-packages\gpiozero\pins\__init__.py", line 358, in <lambda>
    lambda self, value: self._set_frequency(value),
  File "C:\Program Files\Python\lib\site-packages\gpiozero\pins\pigpio.py", line 300, in _set_frequency
    self.factory.connection.set_PWM_frequency(self.number, value)
  File "C:\Program Files\Python\lib\site-packages\pigpio.py", line 1622, in set_PWM_frequency
    _pigpio_command(self.sl, _PI_CMD_PFS, user_gpio, frequency))
  File "C:\Program Files\Python\lib\site-packages\pigpio.py", line 1025, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
struct.error: required argument is not an integer

#### CODE for RPi4 ####

from time import sleep

from gpiozero import TonalBuzzer
from gpiozero.tones import Tone

buzzer = TonalBuzzer(26)

tone = Tone(220.0)
print(type(tone))
print(tone.frequency)
print(tone.note)

buzzer.play(tone)
sleep(2)
buzzer.stop()

**Comment by bennuttall** [comment]
This is a know issue: #712 - there's a fix for it in the issue you might want to try but we've not looked into it yet

closing as duplicate
