### ISSUE TITLE
Temperature and Humidity Sensor

### ISSUE THREAD

**Issue by vaskarni** [gpiozero/gpiozero#978]
Device name: e.g. Temperature & Humidity sensor DHT 11
Protocol: e.g. GPIO
URL of example product:
Further information e.g. data sheet:
https://www.adafruit.com/product/386
Please provide example code for using this device with Python, using another library:

Adafruit has a library that does not work with GPIOZero. Hence requesting adding this device to your library.

**Comment by lurch** [comment]
Duplicate of #254 ?

**Comment by bennuttall** [comment]
This is indeed a duplicate.

Unfortunately this is a nontrivial addition. If you can help, please add comments to #254.
